Algoritmo "Habilitacao"
//  
//  
// Descrição   :
// Autor(a)    : Erik Yen
// Data atual  : 10/06/2020
Var
// Variaveis
idade: inteiro
resp: caracter

Inicio
// Inicio

escreval("Qual a sua idade?")
leia(idade)
escreval("Possui habilitacao?")
 leia(resp)

//Decisao
se ((idade>=18)e(resp="sim")) entao

      escreval("Pode passar!")

senao
     escreval("Nao pode passar!")
fimse


Fimalgoritmo