Algoritmo "Regras para competir"
//  
//  
// Descrição   : verificar se o jogador pode competir ou nao
// Autor(a)    : Erik Yen
// Data atual  : 10/06/2020
Var
// Variaveis
alt :real
idade :inteiro


Inicio
//Inicio
escreval("Qual a sua altura? ")
leia(alt)
escreval("Qual a sua idade? ")
leia(idade)

//processamento
se((alt>=1.75)e(idade>=18)) entao
   escreval("Voce pode competir!")
senao
   escreval("Voce nao pode competir!")
fimse

//Saida



Fimalgoritmo