Algoritmo "15-Melhorescola"
//  
//  
// Descrição   : dizer qual melhor escola de ribeirao pires
// Autor(a)    : Erik yen
// Data atual  : 15/09/2020
Var
// Variaveis

escola:caracter

Inicio
// Inicio
escreval("Digite o nome da melhor escola de Ribeirao Pires")
leia(escola)

enquanto (escola<>"ETEC MCM") faca

      escreval("----------------")
      escreval("Nome incorreto!")

      escreval("Digite denovo:")
      leia(escola)

fimenquanto


Fimalgoritmo