Algoritmo "6-Soma"
//  
//  
// Descrição   : Solicitar 10 numeros inteiros e fornecer a soma deles.
// Autor(a)    : Erik Yen
// Data atual  : 14/09/2020
Var
// Variaveis
cont,num,soma: inteiro


Inicio
// inicio

para cont de 1 ate 10 faca
      escreval("Digite um numero")
      leia(num)
      soma<-soma+num
fimpara
escreval("------------------")
escreval("A soma dos numeros inteiros e:",soma)


Fimalgoritmo